import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Header } from '@/components/shared';

export const metadata: Metadata = {
  title: 'Next Pizza | Home',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, modal }: Readonly<{ children: ReactNode; modal: ReactNode }>) {
  return (
    <main className='min-h-screen'>
      <Header />

      {children}

      {modal}
    </main>
  );
}
